services:
  dev:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run dev
    tty: true
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: Dockerfile

volumes:
  node_modules:
